### ISSUE TITLE
Regression {{#else if}} are splitted into {{else}}{{#if}}

### ISSUE THREAD

**Issue by VincentMolinie** [ember-template-lint/ember-template-lint-plugin-prettier#288]
All my `{{else if}}` are transformed into `{{else}{{#if}}`

Before:
![Capture d’écran 2023-11-29 à 09 47 58](https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/assets/3263749/f09bc12e-605a-4599-87e9-a393d633fdcf)
After:
![Capture d’écran 2023-11-29 à 09 47 51](https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/assets/3263749/bee79314-f5ab-4d85-a3a8-e6954da55d86)

Is this expected 🤔  ?

**Comment by dcyriller** [comment]
No it's not expected. Could you tell me which Prettier version you use?

**Comment by VincentMolinie** [comment]
`Prettier v3.1.0`

**Comment by dcyriller** [comment]
hm I cannot reproduce the issue on my end.

The formatting of "{{#else if}}" is tested here in the prettier codebase:
https://github.com/prettier/prettier/blob/8d64505bd47bddb5f559f4a1eead64a158d81c5a/tests/format/handlebars/block-statement/__snapshots__/jsfmt.spec.js.snap#L629-L635
So the formatting you get is unexpected.

I fixed this issue in the Prettier codebase in 2019. So I wonder if an old Prettier version is not conflicting somehow. Maybe you can try `npm ls prettier` to see if there is not an old Prettier version in the  transitive dependencies.

Another option:  you can try to format with `ember-template-lint --fix .` and with `prettier --write .`. Is there is a difference?

**Comment by VincentMolinie** [comment]
Actually I realised it's not all the else if. This template will break:
```hbs
{{#each @explorerColumn.recordsContext.records as |record|}}
    <Explorer::RecordsList::Item
      @afterDeleteRecords={{this.fetchRecords}}
      @explorerColumn={{@explorerColumn}}
      @record={{record}}
      data-test-records-list-item={{get
        record
        @explorerColumn.displayFieldNamesWithNamespace.firstObject
      }}
    />
  {{else if @explorerColumn.recordsContext.error}}
    <Layout::LayoutError
      @error={{@explorerColumn.recordsContext.error}}
      @withNoBackground={{true}}
    />
  {{else}}
    <DataDisplay::BetaIcon
      @class="c-records-list__empty-icon"
      @iconName={{if
        (or @explorerColumn.recordsContext.filter @explorerColumn.recordsContext.search)
        'search'
        @explorerColumn.field.referenceModel.iconOrDefault
      }}
      @size="custom"
      data-test-records-list-empty-icon
    />
    <span class="c-records-list__empty-text" data-test-records-list-empty-text>
      {{#if
        (or @explorerColumn.recordsContext.filter @explorerColumn.recordsContext.search)
      }}
        No
        {{capitalize-text @explorerColumn.field.displayName}}
        match your search or filters.
      {{else}}
        There are no
        {{capitalize-text @explorerColumn.field.displayName}}
        yet.
      {{/if}}
    </span>
  {{/each}}
```

**Comment by VincentMolinie** [comment]
It's the same issue with `{{#unless}}{{else if}}{{/unless}}`

**Comment by dcyriller** [comment]
oh okay - now I see what the problem is.

The issue here is how `{{#unless}}{{else if}}{{/unless}}` is parsed. First, no error is thrown when being parsed. Second, the output ast is not usable.

If you write:
``<div>{{else if}}</div>`
the syntax is invalid. So the parser will throw an error. This is why ember-template-lint and prettier won't suggest or apply any modifications. But in the case of this syntax, no error is thrown. So the tools consider the syntax as valid and try to make suggestions / modifications, which they should not.

Thank you for reporting this issue. Unfortunately, there is not much we can do in this repo. If you really want to fix the issue, the next step would be to see with the [handlebarsjs](https://github.com/handlebars-lang/handlebars.js/) team.

I put a simplified version of your template in astexplorer ([link](https://astexplorer.net/#/gist/e2540feb73418768a6de3f964bc0add1/19df108e4878505a5a7a0d0a759c51cd7e67975a)). As I can reproduce the issue with handlebars as a parser, it leads me to think the issue is there.
